version: '3.8'

services:
  app:
    image: your_dockerhub_username/myapp:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/h2db/hanzan
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - h2_data:/data/h2db

volumes:
  h2_data:
